config/routes.rb
Myapp::Application.routes.draw do

  resources :disposition_details
  resources :dispositions
  resources :types
  resources :attributes
  resources :mydispositions
  resources :history

# RESOURCE
  resources :roles
  resources :dashboards
  resources :letters
  resources :delegations
  resources :cost_centres
  resources :directorates
  resources :users
    post '/auth' => 'users#auth', foo: 'bar'
    get '/auth' => 'users#auth', foo: 'bar'
  resources :user_activities

# URL
  root to: "sessions#new"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'landing' => 'dashboards#index'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#signup'
  get 'surat' => 'letters#index2'
  get 'histoo' => 'dispositions#history'
  get 'mydis' => 'mydispositions#index'
  get 'home' => 'dashboards#index'
  get 'new_letter_masuk' => 'letters#new'
  get 'new_letter_keluar' => 'letters#new'
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  # get 'my_request' => 'requests#my_index'
  # post 'signup' => 'users#create'


end

app/models/directorate.rb
class Directorate < ActiveRecord::Base
end

app/controllers/directorates_controller.rb
class DirectoratesController < ApplicationController
  before_action :set_directorate, only: [:show, :edit, :update, :destroy]

  # GET /directorates
  # GET /directorates.json
  def index
    @directorates = Directorate.all
  end

  # GET /directorates/1
  # GET /directorates/1.json
  def show
  end

  # GET /directorates/new
  def new
    @directorate = Directorate.new
  end

  # GET /directorates/1/edit
  def edit
  end

  # POST /directorates
  # POST /directorates.json
  def create
    @directorate = Directorate.new(directorate_params)

    respond_to do |format|
      if @directorate.save
        format.html { redirect_to @directorate, notice: 'Directorate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @directorate }
      else
        format.html { render action: 'new' }
        format.json { render json: @directorate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directorates/1
  # PATCH/PUT /directorates/1.json
  def update
    respond_to do |format|
      if @directorate.update(directorate_params)
        format.html { redirect_to @directorate, notice: 'Directorate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @directorate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directorates/1
  # DELETE /directorates/1.json
  def destroy
    @directorate.destroy
    respond_to do |format|
      format.html { redirect_to directorates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directorate
      @directorate = Directorate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directorate_params
      params.require(:directorate).permit(:nama, :keterangan)
    end
end

app/helpers/directorates_helper.rb
module DirectoratesHelper
end

app/views/directorates/_form.html.erb
<%= form_for(@directorate, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @directorate.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@directorate.errors.count, "error") %> prohibited this directorate from being saved:</h4>

      <ul>
      <% @directorate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    
      <%= f.label :nama, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :nama, class: "form-control" %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :keterangan, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :keterangan, class: "form-control" %>
      </div>
    
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/directorates/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Perubahan directorate</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'directorates', '/directorates' %>
            </li>
            <li>
                <strong>Perubahan</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<%= render 'form' %>
	<%= link_to directorates_path, class: 'btn btn-danger' do %>
		Back
	<% end %>
	<%= link_to @directorate, class: 'btn btn-info' do %>
		<span class="glyphicon glyphicon-info-sign"></span>
		Show
	<% end %>
</div>

app/views/directorates/index.html.erb
<% concat ("<div class='alert alert-success alert-dismissable' id='notice'>" + notice + "</div>").html_safe if !notice.nil? %>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Listing directorates</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <strong>directorates</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>directorates</h5>
        <div class="ibox-tools">
            <!-- <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="table_basic.html#">
                <i class="fa fa-wrench"></i>
            </a> -->
            <!-- <ul class="dropdown-menu dropdown-user">
                <li><a href="table_basic.html#">Config option 1</a>
                </li>
                <li><a href="table_basic.html#">Config option 2</a>
                </li>
            </ul> -->
            <%= link_to new_directorate_path do %>
              <span class="fa fa-plus"></span>
              Tambah Direktorat
            <% end %>
            <!-- 
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a> -->
        </div>
    </div>
    <div class="ibox-content" style="display: block;">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama</th>
            
                <th>Keterangan</th>
            
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <%= content_tag_for(:tr, @directorates) do |directorate| %>

                <td><%= directorate.id %></td>
                <td><%= directorate.nama %></td>
            
                <td><%= directorate.keterangan %></td>
            
                <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, directorate %></td>
                <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_directorate_path(directorate) %></td>
                <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, directorate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

<br>

app/views/directorates/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>directorate Baru</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'directorates', '/directorates' %>
            </li>
            <li>
                <strong>directorate Baru</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<%= render 'form' %>
	<%= link_to directorates_path, class: 'btn btn-danger' do %>
		Back
	<% end %>
</div>

app/views/directorates/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>directorate Detail</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'directorates', '/directorates' %>
            </li>
            <li>
                <strong>Detail</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Informasi Detail</h5>
          <div class="ibox-tools">
              <%= link_to edit_directorate_path(@directorate) do %>
                <span class="fa fa-edit"></span>
                Edit
              <% end %>
          </div>
      </div>
      <div class="ibox-content" style="display: block;">
        <table class="table table-bordered">

            <tr>
              <td><strong>Nama:</strong></td>
              <td><%= @directorate.nama %></td>
            </tr>

            <tr>
              <td><strong>Keterangan:</strong></td>
              <td><%= @directorate.keterangan %></td>
            </tr>

        </table>
      </div>
    </div>
  </div>
</div>

<%= link_to directorates_path, class: 'btn btn-danger' do %>
    Back
  <% end %>