config/routes.rb
Myapp::Application.routes.draw do

  resources :disposition_details
  resources :dispositions
  resources :types
  resources :attributes
  resources :mydispositions
  resources :history

# RESOURCE
  resources :roles
  resources :dashboards
  resources :letters
  resources :delegations
  resources :cost_centres
  resources :directorates
  resources :users
    post '/auth' => 'users#auth', foo: 'bar'
    get '/auth' => 'users#auth', foo: 'bar'
  resources :user_activities

# URL
  root to: "sessions#new"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'landing' => 'dashboards#index'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#signup'
  get 'surat' => 'letters#index2'
  get 'histoo' => 'dispositions#history'
  get 'mydis' => 'mydispositions#index'
  get 'home' => 'dashboards#index'
  get 'new_letter_masuk' => 'letters#new'
  get 'new_letter_keluar' => 'letters#new'
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  # get 'my_request' => 'requests#my_index'
  # post 'signup' => 'users#create'


end

app/models/disposition.rb
class Disposition < ActiveRecord::Base
  # include ActiveModel::Model
  #
  # attr_accessor :nomor, :penerima
  #
  # def save
  #   return false if invalid?
  #
  #   ActiveRecord::Base.transaction do
  #     detail = DispositionDetail.create!(nomor: nomor, penerima: penerima)
  #   end
  #
  #   true
  # rescue ActiveRecord::StatementInvalid => e
  #   # Handle exception that caused the transaction to fail
  #   # e.message and e.cause.message can be helpful
  #   errors.add(:base, e.message)
  #
  #   false
  # end

  has_many :disposition_details
  belongs_to :letter
end

app/controllers/dispositions_controller.rb
class DispositionsController < ApplicationController
  before_action :set_disposition, only: [:show, :edit, :update, :destroy]

  # GET /dispositions
  # GET /dispositions.json
  def index
    if  current_user.role=='direksi' || current_user.role=='kadiv' || current_user.role=='admin'
      @dispositions = Disposition.where('penerima'=>current_user.username)

    elsif current_user.role=='sekretaris_direksi' || current_user.role=='admin'
      @dispositions = Disposition.where('penerima'=>CostCentre.find_by_kode(current_user.cost_centre_id).pejabat)

    else
      @dispositions = Disposition.all
    end
  end

  def history
    if  current_user.role=='direksi' || current_user.role=='kadiv' || current_user.role=='admin'
      @dispositions = Disposition.where('pemberi'=>current_user.username)
      @details = DispositionDetail.all
    elsif current_user.role=='sekretaris_direksi' || current_user.role=='admin'
      @dispositions = Disposition.where('pemberi'=>CostCentre.find_by_kode(current_user.cost_centre_id).pejabat)
      @details = DispositionDetail.all
    else
      @dispositions = Disposition.all
      @details = DispositionDetail.all
    end
    
  end
  # GET /dispositions/1
  # GET /dispositions/1.json
  def show
    @nomor = Disposition.find(params[:id]).nomor
    @detail = DispositionDetail.where("nomor"=>@nomor)
  end

  # GET /dispositions/new
  def new
    @disposition = Disposition.new
  end

  # GET /dispositions/1/edit
  def edit
  end

  # POST /dispositions
  # POST /dispositions.json
  def create
    @disposition = Disposition.new(disposition_params)


    respond_to do |format|
      if @disposition.save
        format.html { redirect_to @disposition, notice: 'Disposition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @disposition }
      else
        format.html { render action: 'new' }
        format.json { render json: @disposition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dispositions/1
  # PATCH/PUT /dispositions/1.json
  def update
    respond_to do |format|
      if @disposition.update(disposition_params)
        format.html { redirect_to @disposition, notice: 'Disposition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @disposition.errors, status: :unprocessable_entity }
      end
    endi
  end

  # DELETE /dispositions/1
  # DELETE /dispositions/1.json
  def destroy
    @disposition.destroy
    respond_to do |format|
      format.html { redirect_to dispositions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disposition
      @disposition = Disposition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disposition_params
      params.require(:disposition).permit(:nomor, :letter_id, :instruksi, :tgl, :status, :laporan, :penerima, :pemberi, :cost_centre_pemberi_id, :cost_centre_penerima_id)
    end
  end
end

app/helpers/dispositions_helper.rb
module DispositionsHelper
end

app/views/dispositions/_form.html.erb
<%= form_for(@disposition, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @disposition.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@disposition.errors.count, "error") %> prohibited this disposition from being saved:</h4>

      <ul>
      <% @disposition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    
      <%= f.label :nomor, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :nomor, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    
      <%= f.label :letter_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :letter_id, class: "form-control" , value:params[:letter_id]%>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :instruksi, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :instruksi, class: "form-control" %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :tgl, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.date_select :tgl, class: "form-control" %>
      </div>
    
  </div>


  <div class="form-group">

      <%= f.label :pemberi, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <% if current_user.role=='direktur'|| current_user.role=='direksi' || current_user.role=='kadiv' %>
        <%= f.text_field :pemberi, class: "form-control", :disabled=>true, value:current_user.nama %>
          <% else %>
          <%= f.text_field :pemberi, class: "form-control", :disabled=>true, value:User.find_by_username(CostCentre.find_by_kode(current_user.cost_centre_id).pejabat).nama %>
        <% end %>
      </div>

  </div>

  <div class="form-group">

      <%= f.label :cost_centre_pemberi_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.number_field :cost_centre_pemberi_id, class: "form-control", :disabled=>true, value:current_user.cost_centre_id %>
      </div>

  </div>





  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/dispositions/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Perubahan disposition</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'dispositions', '/dispositions' %>
            </li>
            <li>
                <strong>Perubahan</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<%= render 'form' %>
	<%= link_to dispositions_path, class: 'btn btn-danger' do %>
		Back
	<% end %>
	<%= link_to @disposition, class: 'btn btn-info' do %>
		<span class="glyphicon glyphicon-info-sign"></span>
		Show
	<% end %>
</div>

app/views/dispositions/history.html.erb
<% concat ("<div class='alert alert-success alert-dismissable' id='notice'>" + notice + "</div>").html_safe if !notice.nil? %>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Riwayat Disposisi</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <strong>dispositions</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">

  </div>
</div>

<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>dispositions</h5>
    <div class="ibox-tools">
      <!-- <a class="collapse-link">
          <i class="fa fa-chevron-up"></i>
      </a>
      <a class="dropdown-toggle" data-toggle="dropdown" href="table_basic.html#">
          <i class="fa fa-wrench"></i>
      </a> -->
      <!-- <ul class="dropdown-menu dropdown-user">
          <li><a href="table_basic.html#">Config option 1</a>
          </li>
          <li><a href="table_basic.html#">Config option 2</a>
          </li>
      </ul> -->
      <!--
      <a class="close-link">
          <i class="fa fa-times"></i>
      </a> -->
    </div>
  </div>
  <div class="ibox-content" style="display: block;">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover dataTables-example">
        <thead>
        <tr>

          <th>Nomor Disposisi</th>


          <th>Instruksi</th>

          <th>Tgl</th>

          <th>Pemberi</th>

          <th>Penerima</th>

          <th>Status</th>

          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <%= content_tag_for(:tr, @dispositions) do |disposition| %>

          <td><%= disposition.nomor %></td>

          <td><%= disposition.instruksi %></td>

          <td><%= disposition.tgl %></td>

          <td><%= disposition.pemberi %></td>

          <td>
          </td>

          <td>
          </td>


          <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, disposition %></td>
          <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, disposition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

<script type="text/javascript">


    $(function() {

        $('.dataTables-example').dataTable({
            "dom": 'T<"clear">lfrtip',
            "tableTools": {
                "sSwfPath": "../assets/dataTables/swf/copy_csv_xls_pdf.swf"
            }
        });
        function numberWithCommas(x) {
            x= x.replace(".",",")
            return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
        }

        $( document ).ready(function() {
            $(".money").each(function(){
                $(this).html(numberWithCommas($(this).html()))
            });
        });
    });
</script>

app/views/dispositions/index.html.erb
<% concat ("<div class='alert alert-success alert-dismissable' id='notice'>" + notice + "</div>").html_safe if !notice.nil? %>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Daftar Disposisi</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <strong>dispositions</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>Disposisi</h5>
        <div class="ibox-tools">
            <!-- <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="table_basic.html#">
                <i class="fa fa-wrench"></i>
            </a> -->
            <!-- <ul class="dropdown-menu dropdown-user">
                <li><a href="table_basic.html#">Config option 1</a>
                </li>
                <li><a href="table_basic.html#">Config option 2</a>
                </li>
            </ul> -->

            <!-- 
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a> -->
        </div>
    </div>
    <div class="ibox-content" style="display: block;">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
            
                <th>Nomor</th>
            
                <th>Nomor Surat</th>
            
                <th>Instruksi</th>
            
                <th>Tgl</th>

                <th>Pemberi</th>


                <th>Status</th>
            
                <th></th>
              </tr>
            </thead>

            <tbody>
              <%= content_tag_for(:tr, @dispositions) do |disposition| %>
            
                <td><%= disposition.nomor %></td>
            
                <td><%= disposition.letter_id %></td>
            
                <td><%= disposition.instruksi %></td>
            
                <td><%= disposition.tgl %></td>
            
                <td><%= disposition.pemberi %></td>

                <td><%= disposition.status %></td>
            
                <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, disposition %></td>
                <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

<br>

app/views/dispositions/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>disposition Baru</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'dispositions', '/dispositions' %>
            </li>
            <li>
                <strong>Disposisi Baru</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<%= render 'form' %>
	<%= link_to dispositions_path, class: 'btn btn-danger' do %>
		Back
	<% end %>
</div>

app/views/dispositions/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Detail Disposisi</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'dispositions', '/dispositions' %>
            </li>
            <li>
                <strong>Detail</strong>
            </li>
        </ol>
      <br>

        <%= link_to mydis_url, class: 'btn btn-danger' do %>
          Back
        <% end %>

      <% if current_user.role!='dirut' || current_user.role!='sekretaris_dirut'%>
        <%# if before=='disposition_path'%>
          <%= link_to new_disposition_path, class: 'btn btn-info' do %>
            Disposisikan
          <% end %>
        <%# end %>

        <%= link_to '', class: 'btn btn-primary' do %>
          Lapor
        <% end %>
      <% end %>

    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Informasi Detail</h5>
          <div class="ibox-tools">
              <%= link_to edit_disposition_path(@disposition) do %>
                <span class="fa fa-edit"></span>
                Edit
              <% end %>
          </div>
      </div>
      <div class="ibox-content" style="display: block;">
        <table class="table table-bordered">
          <tr>
            <td><strong>Nomor:</strong></td>
            <td><%= @disposition.nomor %></td>
          </tr>

          <tr>
            <td><strong>Letter:</strong></td>
            <td><%= @disposition.letter_id %></td>
          </tr>

          <tr>
            <td><strong>Instruksi:</strong></td>
            <td><%= @disposition.instruksi %></td>
          </tr>

          <tr>
            <td><strong>Tgl:</strong></td>
            <td><%= @disposition.tgl %></td>
          </tr>

          <tr>
            <td><strong>Pemberi:</strong></td>
            <td><%= @disposition.pemberi %></td>
          </tr>

          <tr>
            <td><strong>Cost centre pemberi:</strong></td>
            <td><%= CostCentre.find_by_kode(@disposition.cost_centre_pemberi_id).nama %></td>
          </tr>

          <% if current_user.role!='staf'%>
          <%= content_tag_for(:tr, @detail) do |det| %>

            <tr>
              <td><strong>Penerima:</strong></td>
              <td><%= det.penerima %></td>
            </tr>


            <tr>
              <td><strong>Cost centre penerima:</strong></td>
              <td><%= CostCentre.find_by_kode(det.cost_centre_penerima_id).nama %></td>
            </tr>


            <tr>
              <td><strong>Status:</strong></td>
              <td><%= det.status %></td>
            </tr>

            <tr>
              <td><strong>Laporan:</strong></td>
              <td><%= det.laporan %></td>
            </tr>

          <% end %>
            <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
