config/routes.rb
Myapp::Application.routes.draw do

  resources :disposition_details
  resources :dispositions
  resources :types
  resources :attributes
  resources :mydispositions
  resources :history

# RESOURCE
  resources :roles
  resources :dashboards
  resources :letters
  resources :delegations
  resources :cost_centres
  resources :directorates
  resources :users
    post '/auth' => 'users#auth', foo: 'bar'
    get '/auth' => 'users#auth', foo: 'bar'
  resources :user_activities

# URL
  root to: "sessions#new"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'landing' => 'dashboards#index'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#signup'
  get 'surat' => 'letters#index2'
  get 'histoo' => 'dispositions#history'
  get 'mydis' => 'mydispositions#index'
  get 'home' => 'dashboards#index'
  get 'new_letter_masuk' => 'letters#new'
  get 'new_letter_keluar' => 'letters#new'
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  # get 'my_request' => 'requests#my_index'
  # post 'signup' => 'users#create'


end

app/models/letter.rb
class Letter < ActiveRecord::Base
  has_one :disposition
  max_paginates_per 50


end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show, :edit, :update, :destroy]

  # GET /letters
  # GET /letters.json
  def index

    if logged_in?
      @a = current_user.username

      if current_user.role =='dirut' || current_user.role =='direksi' || current_user.role =='kadiv'

        @letters = Letter.all.where('penerima'=>@a)

      else
             @letters = Letter.all
      end
    end
  end

  def index2

    if logged_in?
      @cs = current_user.cost_centre_id
      @pejabat = CostCentre.find_by_kode(@cs).pejabat


      if current_user.role == 'sekretaris_dirut' || current_user.role=='sekretaris_direksi' || current_user.role=='admin'
        @letters_masuk = Letter.where('penerima'=>@pejabat)
        @letters_keluar = Letter.where('pengirim'=>@pejabat)

      else
        @letter = Letter.all

      end
    end

  end

  # GET /letters/1
  # GET /letters/1.json
  def show
  end


  # GET /letters/new
  def new
    @letter = Letter.new
  end


  # GET /letters/1/edit
  def edit
  end

  # POST /letters
  # POST /letters.json
  def create()
    @letter = Letter.new(letter_params)
    @pejabat = CostCentre.find_by_kode(current_user.cost_centre_id).pejabat

    @letter.penerima = @pejabat

    if request.url=='new_letter_keluar'
      @letter.pengirim = CostCentre.find_by_kode(current_user.cost_centre_id).pejabat
    else
      @pen = CostCentre.find_by_kode(current_user.cost_centre_id).pejabat
      @letter.penerima = User.find_by_nama(@pen).email
      @letter.cost_centre_id = current_user.cost_centre_id
    end

    if(!params[:letter][:nama_file].nil?)
      uploaded_io = params[:letter][:nama_file]
      file_path = File.join('uploads/surat', Time.new.strftime("surat_%Y%m%d%H%M%S%L_" + uploaded_io.original_filename.gsub(/[^.a-zA-Z0-9_-]*/, '')))
      File.open(Rails.root.join('app/assets', file_path), 'wb') do |file|
        file.write(uploaded_io.read)
      end
      @letter.nama_file = file_path
    end

    respond_to do |format|
      if @letter.save

        # @us = User.find_by_nama(@letter.penerima)
        # UserMailer.inbox_email(@letter, @us).deliver_now
        #
        # if @letter.delegasi!=""
        #   @del = User.find_by_nama(@letter.delegasi)
        #
        # end

        format.html { redirect_to @letter, notice: 'Letter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @letter }
      else
        format.html { render action: 'new' }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /letters/1
  # PATCH/PUT /letters/1.json
  def update
    respond_to do |format|
      if @letter.update(letter_params)
        format.html { redirect_to @letter, notice: 'Letter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  def destroy
    @letter.destroy
    respond_to do |format|
      format.html { redirect_to letters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_params
      params.require(:letter).permit(:no_surat, :sifat, :jenis, :pengirim, :penerima, :asal_surat, :perihal, :tgl_surat, :tgl_terima, :cost_centre_id, :directorate_id, :nama_file, :status, :delegasi)
    end
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/letters/_form.html.erb
<%= form_for(@letter, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @letter.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@letter.errors.count, "error") %> prohibited this letter from being saved:</h4>

      <ul>
      <% @letter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label :no_surat, class: "col-sm-2 control-label" %>
      <div class="col-sm-6" >
        <%= f.text_field :no_surat, class: "form-control", :required => "true"%>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :sifat, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= collection_select(:letter, :sifat, Attribute.all, :nama, :nama,{prompt: "Pilih Sifat"},{:class => 'form-control', :required => "true"}) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :"Jenis", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= collection_select(:letter, :jenis, Type.all, :nama, :nama,{prompt: "Pilih Jenis"},{:class => 'form-control', :required => "true"}) %>
    </div>
  </div>


<!--CEK SURAT KELUAR ATAU BUKAN-->
<% if current_page?(new_letter_keluar_url) %>
    <div class="form-group">
      <%= f.label :asal_surat, class: "col-sm-2 control-label"%>
      <div class="col-sm-6">
        <%= f.text_field :asal_surat, :class => "form-control", :disabled=>true, value:'Internal'  %>
      </div>
    </div>

    <div class="form-group">
        <%= f.label :pengirim, class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :pengirim, class: "form-control", :disabled=>true, value:CostCentre.find_by_kode(current_user.cost_centre_id).pejabat %>
        </div>
    </div>

    <div class="form-group">
      <%= f.label :penerima, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= collection_select(:letter, :penerima, User.all, :nama, :nama,{prompt: "Penerima"},{:class => 'form-control', :required => "true"}) %>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :cost_centre_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= collection_select(:letter, :cost_centre_id, CostCentre.all, :kode, :nama,{prompt: "Cost Centre Penerima"},{:class => 'form-control', :required => "true"}) %>
      </div>

    </div>

<% else %>
    <div class="form-group">
      <%= f.label :asal_surat, class: "col-sm-2 control-label"%>
      <div class="col-sm-6">
        <%= f.select :asal_surat, [['Internal'],['Eksternal']],{},{:class => "form-control", :required => "true"}  %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :pengirim, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :pengirim, class: "form-control", :required => "true"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :penerima, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :penerima, class: "form-control", value:CostCentre.find_by_kode(current_user.cost_centre_id).pejabat, :disabled=>true%>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :cost_centre_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.number_field :cost_centre_id, class: "form-control" , value:current_user.cost_centre_id, :disabled=>true%>
      </div>

    </div>
<% end %>

  <div class="form-group">
    
      <%= f.label :perihal, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :perihal, class: "form-control" , :required => "true"%>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :tgl_surat, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.date_select :tgl_surat, class: "form-control" , :required => "true"%>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :tgl_terima, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.date_select :tgl_terima, class: "form-control", :required => "true" %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :directorate_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= collection_select(:letter, :directorate_id, Directorate.all, :id, :nama,{prompt: "Direktorat Penerima"},{:required => "true",:class => 'form-control'}) %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :nama_file, class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.file_field :nama_file, :class => 'form-control' , :required => "true"%>
    </div>
    
  </div>

  <div class="form-group hidden">
      <%= f.label :status, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">

        <% if current_page?(new_letter_masuk_url) || current_page?(new_letter_keluar_url) %>
                <%= f.text_field :status, class: "form-control", value:'NotRead'%>
        <% else %>
                  <%= f.text_field :status, class: "form-control"%>
        <% end %>

      </div>
  </div>



  <div class="form-group hidden">
      <%= f.label :delegasi, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
          <%= f.text_field :delegasi, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/letters/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Perubahan letter</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'letters', '/letters' %>
            </li>
            <li>
                <strong>Perubahan</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<%= render 'form' %>
	<%= link_to letters_path, class: 'btn btn-danger' do %>
		Back
	<% end %>
	<%= link_to @letter, class: 'btn btn-info' do %>
		<span class="glyphicon glyphicon-info-sign"></span>
		Show
	<% end %>
</div>

app/views/letters/index.html.erb
<% concat ("<div class='alert alert-success alert-dismissable' id='notice'>" + notice + "</div>").html_safe if !notice.nil? %>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Daftar Surat</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <strong>letters</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>Surat Masuk</h5>
        <div class="ibox-tools">
            <!-- <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="table_basic.html#">
                <i class="fa fa-wrench"></i>
            </a> -->
            <!-- <ul class="dropdown-menu dropdown-user">
                <li><a href="table_basic.html#">Config option 1</a>
                </li>
                <li><a href="table_basic.html#">Config option 2</a>
                </li>
            </ul> -->
            <!--
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a> -->
        </div>
    </div>

    <div class="ibox-content" style="display: block;">

        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
              <tr>

                <th>No surat</th>
                <th>Sifat</th>
                <th>Jenis</th>
                <th>Pengirim</th>
                <th>Perihal</th>
                <th>Tgl surat</th>
                <th>Dispo</th>
                <th>Status</th>

                <th></th>
              </tr>
            </thead>

            <tbody>

              <%= content_tag_for(:tr, @letters) do |letter| %>

                <td><%= letter.no_surat %></td>
                <td><%= letter.sifat %></td>
                <td><%= letter.jenis %></td>
                <td><%= letter.pengirim %></td>
                <td><%= letter.perihal %></td>
                <td><%= letter.tgl_surat %></td>

                <% if letter.status=="NotRead" %>
                  <td><%= link_to '<i class="fa fa-inbox"></i>'.html_safe, new_disposition_path(:letter_id => letter.no_surat)%></td>
                <% else %>
                  <td><i class="fa fa-inbox" type="hidden"></i></td>
                <% end %>

                <td><%= letter.status %></td>

                <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, letter %></td>

                <% if current_user.role=='superadmin'%>
                <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, letter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

<br>


<script type="text/javascript">


    $(function() {

        $('.dataTables-example').dataTable({
            "dom": 'T<"clear">lfrtip',
            "tableTools": {
                "sSwfPath": "../assets/dataTables/swf/copy_csv_xls_pdf.swf"
            }
        });
        function numberWithCommas(x) {
            x= x.replace(".",",")
            return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
        }

        $( document ).ready(function() {
            $(".money").each(function(){
                $(this).html(numberWithCommas($(this).html()))
            });
        });
    });
</script>

app/views/letters/index2.html.erb
<% concat ("<div class='alert alert-success alert-dismissable' id='notice'>" + notice + "</div>").html_safe if !notice.nil? %>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Daftar Surat</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <strong>letters</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="ibox float-e-margins">

            <!-- <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="table_basic.html#">
                <i class="fa fa-wrench"></i>
            </a> -->
            <!-- <ul class="dropdown-menu dropdown-user">
                <li><a href="table_basic.html#">Config option 1</a>
                </li>
                <li><a href="table_basic.html#">Config option 2</a>
                </li>
            </ul> -->

            <!--
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a> -->


        <div class="ibox-content" style="display: block;">

            <div class="panel blank-panel">

                <div class="panel-options">

                  <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-masuk">Surat Masuk</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-keluar">Surat Keluar</a></li>
                  </ul>
                </div>
              </div>

              <div class="panel-body">

                <div class="tab-content">
<!-- TAB 1                 -->
                  <div id="tab-masuk" class="tab-pane active">
                    <%= link_to new_letter_masuk_url do %>
                      <span class="fa fa-plus"></span>
                      Tambah Surat Masuk
                    <% end %>
                    <div class="table-responsive">
                      <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>

                          <th>No surat</th>
                          <th>Sifat</th>
                          <th>Pengirim</th>
                          <th>Perihal</th>
                          <th>Tgl surat</th>
                          <th>Dispo</th>
                          <th>Status</th>

                          <th></th>
                          <th></th>
                          <th></th>
                        </tr>
                        </thead>

                        <tbody>
                        <%= content_tag_for(:tr, @letters_masuk) do |letter| %>

                          <td><%= letter.no_surat %></td>
                          <td><%= letter.sifat %></td>
                          <td><%= letter.pengirim %></td>
                          <td><%= letter.perihal %></td>
                          <td><%= letter.tgl_surat %></td>

                          <% if letter.status=="NotRead" %>
                            <td><%= link_to '<i class="fa fa-inbox"></i>'.html_safe, new_disposition_path%></td>
                          <% else %>
                            <td><i class="fa fa-inbox" type="hidden"></i></td>
                          <% end %>

                          <td><%= letter.status %></td>

                          <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, letter %></td>
                          <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_letter_path(letter) %></td>
                          <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, letter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div>
<!--TAB 2-->
                  <div id="tab-keluar" class="tab-pane">
                    <%= link_to new_letter_keluar_url do %>
                      <span class="fa fa-plus"></span>
                      Tambah Surat Keluar
                    <% end %>

                    <div class="table-responsive">
                      <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>

                          <th>No surat</th>
                          <th>Sifat</th>
                          <th>Dikirim kepada</th>
                          <th>Perihal</th>
                          <th>Tgl surat</th>
                          <th>Status</th>

                          <th></th>
                          <th></th>
                          <th></th>
                        </tr>
                        </thead>

                        <tbody>
                        <%= content_tag_for(:tr, @letters_keluar) do |letter| %>

                          <td><%= letter.no_surat %></td>
                          <td><%= letter.sifat %></td>
                          <td><%= letter.penerima %></td>
                          <td><%= letter.perihal %></td>
                          <td><%= letter.tgl_surat %></td>
                          <td><%= letter.status %></td>

                          <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, letter %></td>
                          <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_letter_path(letter) %></td>
                          <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, letter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        <% end %>
                        </tbody>
                      </table>

                  </div>

              </div>
           </div>

        </div>
      </div>

    </div>
</div>

<br>

app/views/letters/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Surat Baru</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'letters', '/letters' %>
            </li>
            <li>
                <strong>Surat Baru</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<%= render 'form' %>
	<%= link_to letters_path, class: 'btn btn-danger' do %>
		Back
	<% end %>
</div>

app/views/letters/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>letter Detail</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'letters', '/letters' %>
            </li>
            <li>
                <strong>Detail</strong>
            </li>
        </ol>
      <br>
      <%= link_to letters_path, class: 'btn btn-danger' do %>
        Back
      <% end %>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Informasi Detail</h5>
          <div class="ibox-tools">

          </div>
      </div>
      <div class="ibox-content" style="display: block;">
        <table class="table table-bordered">

            <tr>
              <td><strong>No surat:</strong></td>
              <td><%= @letter.no_surat %></td>
            </tr>

            <tr>
              <td><strong>Sifat:</strong></td>
              <td><%= @letter.sifat %></td>
            </tr>

            <tr>
              <td><strong>Jenis:</strong></td>
              <td><%= @letter.jenis %></td>
            </tr>

            <tr>
              <td><strong>Pengirim:</strong></td>
              <td><%= @letter.pengirim %></td>
            </tr>

            <tr>
              <td><strong>Penerima:</strong></td>
              <td><%= @letter.penerima %></td>
            </tr>

            <tr>
              <td><strong>Asal surat:</strong></td>
              <td><%= @letter.asal_surat %></td>
            </tr>

            <tr>
              <td><strong>Perihal:</strong></td>
              <td><%= @letter.perihal %></td>
            </tr>

            <tr>
              <td><strong>Tgl surat:</strong></td>
              <td><%= @letter.tgl_surat %></td>
            </tr>

            <tr>
              <td><strong>Tgl terima:</strong></td>
              <td><%= @letter.tgl_terima %></td>
            </tr>

            <tr>
              <td><strong>Cost centre:</strong></td>
              <td><%= @letter.cost_centre_id %></td>
            </tr>

            <tr>
              <td><strong>Directorate:</strong></td>
              <td><%= @letter.directorate_id %></td>
            </tr>

            <tr>
              <td><strong>Nama file:</strong></td>
              <td><%= @letter.nama_file %>
                <%= @b=@letter.nama_file %>
              </td>
            </tr>

            <tr>
              <td><strong>Status:</strong></td>
              <td><%= @letter.status %></td>
            </tr>

            <tr>
              <td><strong>Delegasi:</strong></td>
              <td><%= @letter.delegasi %></td>
            </tr>
        </table>
        <iframe src="<%= link_to "display using the full viewer", pdfjs.full_path(file: "/assets/uploads/surat/surat_20180820145007767_1577-1-10744-1-10-201709131.pdf") %>"></iframe>
      </div>
    </div>
  </div>
</div>
