config/routes.rb
Myapp::Application.routes.draw do

  resources :disposition_details
  resources :dispositions
  resources :types
  resources :attributes
  resources :mydispositions
  resources :history

# RESOURCE
  resources :roles
  resources :dashboards
  resources :letters
  resources :delegations
  resources :cost_centres
  resources :directorates
  resources :users
    post '/auth' => 'users#auth', foo: 'bar'
    get '/auth' => 'users#auth', foo: 'bar'
  resources :user_activities

# URL
  root to: "sessions#new"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'landing' => 'dashboards#index'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#signup'
  get 'surat' => 'letters#index2'
  get 'histoo' => 'dispositions#history'
  get 'mydis' => 'mydispositions#index'
  get 'home' => 'dashboards#index'
  get 'new_letter_masuk' => 'letters#new'
  get 'new_letter_keluar' => 'letters#new'
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  # get 'my_request' => 'requests#my_index'
  # post 'signup' => 'users#create'


end

app/models/delegation.rb
class Delegation < ActiveRecord::Base
end

app/controllers/delegations_controller.rb
class DelegationsController < ApplicationController
  before_action :set_delegation, only: [:show, :edit, :update, :destroy]

  # GET /delegations
  # GET /delegations.json
  def index
    @pejabat = CostCentre.find_by_kode(current_user.cost_centre_id).pejabat
    @delegations = Delegation.where('pemberi'=>@pejabat)
  end

  # GET /delegations/1
  # GET /delegations/1.json
  def show
  end

  # GET /delegations/new
  def new
    @delegation = Delegation.new
  end

  # GET /delegations/1/edit
  def edit
  end

  # POST /delegations
  # POST /delegations.json
  def create
    @delegation = Delegation.new(delegation_params)

    @delegation.cost_centre_pemberi_id = CostCentre.find_by_kode(current_user.cost_centre_id).kode

    respond_to do |format|
      if @delegation.save
        format.html { redirect_to @delegation, notice: 'Delegation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @delegation }
      else
        format.html { render action: 'new' }
        format.json { render json: @delegation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delegations/1
  # PATCH/PUT /delegations/1.json
  def update
    respond_to do |format|
      if @delegation.update(delegation_params)
        format.html { redirect_to @delegation, notice: 'Delegation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @delegation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delegations/1
  # DELETE /delegations/1.json
  def destroy
    @delegation.destroy
    respond_to do |format|
      format.html { redirect_to delegations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delegation
      @delegation = Delegation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delegation_params
      params.require(:delegation).permit(:nomor, :mulai, :selesai, :pemberi, :cost_centre_pemberi_id, :penerima, :cost_centre_penerima_id, :keterangan)
    end
end

app/helpers/delegations_helper.rb
module DelegationsHelper
end

app/views/delegations/_form.html.erb
<%= form_for(@delegation, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @delegation.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@delegation.errors.count, "error") %> prohibited this delegation from being saved:</h4>

      <ul>
      <% @delegation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    
      <%= f.label :nomor, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :nomor, class: "form-control" %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :mulai, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.date_select :mulai, class: "form-control" %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :selesai, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.date_select :selesai, class: "form-control" %>
      </div>
    
  </div>

  <div class="form-group">
      <%= f.label :pemberi, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :pemberi, class: "form-control" , value: CostCentre.find_by_kode(current_user.cost_centre_id).pejabat %>
      </div>
    
  </div>

  <div class="form-group hidden">
      <%= f.label :cost_centre_pemberi_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :cost_centre_pemberi_id %>
      </div>
  </div>

  <div class="form-group">
    
      <%= f.label :penerima, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= collection_select(:delegation, :penerima, User.all, :email, :nama,{prompt: "Penerima"},{:class => 'form-control'}) %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :cost_centre_penerima_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= collection_select(:delegation, :cost_centre_penerima_id, CostCentre.all, :kode, :nama,{prompt: "Cost Center Penerima"},{:class => 'form-control'}) %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :keterangan, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :keterangan, class: "form-control" %>
      </div>
    
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/delegations/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Perubahan delegation</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'delegations', '/delegations' %>
            </li>
            <li>
                <strong>Perubahan</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<%= render 'form' %>
	<%= link_to delegations_path, class: 'btn btn-danger' do %>
		Back
	<% end %>
	<%= link_to @delegation, class: 'btn btn-info' do %>
		<span class="glyphicon glyphicon-info-sign"></span>
		Show
	<% end %>
</div>

app/views/delegations/index.html.erb
<% concat ("<div class='alert alert-success alert-dismissable' id='notice'>" + notice + "</div>").html_safe if !notice.nil? %>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Daftar Delegasi</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <strong>delegations</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>Delegasi</h5>
        <div class="ibox-tools">
            <!-- <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="table_basic.html#">
                <i class="fa fa-wrench"></i>
            </a> -->
            <!-- <ul class="dropdown-menu dropdown-user">
                <li><a href="table_basic.html#">Config option 1</a>
                </li>
                <li><a href="table_basic.html#">Config option 2</a>
                </li>
            </ul> -->
            <%= link_to new_delegation_path do %>
              <span class="fa fa-plus"></span>
              Tambah Delegasi
            <% end %>
            <!-- 
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a> -->
        </div>
    </div>
    <div class="ibox-content" style="display: block;">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
            
                <th>Nomor</th>
            
                <th>Mulai</th>
            
                <th>Selesai</th>
            
                <th>Pemberi</th>
            
                <th>Penerima</th>
            
                <th>Keterangan</th>
            
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <%= content_tag_for(:tr, @delegations) do |delegation| %>
            
                <td><%= delegation.nomor %></td>
            
                <td><%= delegation.mulai %></td>
            
                <td><%= delegation.selesai %></td>
            
                <td><%= delegation.pemberi %></td>
            
                <td><%= delegation.penerima %></td>
            
                <td><%= delegation.keterangan %></td>
            
                <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, delegation %></td>
                <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_delegation_path(delegation) %></td>
                <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, delegation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

<br>

app/views/delegations/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>delegation Baru</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'delegations', '/delegations' %>
            </li>
            <li>
                <strong>Delegasi Baru</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<%= render 'form' %>
	<%= link_to delegations_path, class: 'btn btn-danger' do %>
		Back
	<% end %>
</div>

app/views/delegations/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>delegation Detail</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <li>
                <%= link_to 'delegations', '/delegations' %>
            </li>
            <li>
                <strong>Detail</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Informasi Detail</h5>
          <div class="ibox-tools">
              <%= link_to edit_delegation_path(@delegation) do %>
                <span class="fa fa-edit"></span>
                Edit
              <% end %>
          </div>
      </div>
      <div class="ibox-content" style="display: block;">
        <table class="table table-bordered">

            <tr>
              <td><strong>Nomor:</strong></td>
              <td><%= @delegation.nomor %></td>
            </tr>

            <tr>
              <td><strong>Mulai:</strong></td>
              <td><%= @delegation.mulai %></td>
            </tr>

            <tr>
              <td><strong>Selesai:</strong></td>
              <td><%= @delegation.selesai %></td>
            </tr>

            <tr>
              <td><strong>Pemberi:</strong></td>
              <td><%= @delegation.pemberi %></td>
            </tr>

            <tr>
              <td><strong>Cost centre pemberi:</strong></td>
              <td><%= @delegation.cost_centre_pemberi_id %></td>
            </tr>

            <tr>
              <td><strong>Penerima:</strong></td>
              <td><%= @delegation.penerima %></td>
            </tr>

            <tr>
              <td><strong>Cost centre penerima:</strong></td>
              <td><%= @delegation.cost_centre_penerima_id %></td>
            </tr>

            <tr>
              <td><strong>Keterangan:</strong></td>
              <td><%= @delegation.keterangan %></td>
            </tr>

        </table>

        <%= link_to delegations_path, class: 'btn btn-danger' do %>
          Back
        <% end %>
      </div>
    </div>
  </div>
</div>
